### ISSUE TITLE
block to page will lose the block reference

### ISSUE THREAD

**Issue by karlz97** [hyrijk/logseq-plugin-block-to-page#1]
This plugin was so cool, I want this feature since I begin to use logseq. Thank you very much for creating it. 
Currently, when the block or its sub block has been referred, 'turn to page' will make the reference invalid. 
It will be perfect if you can find a way to solve it! thanks again!

**Comment by hyrijk** [comment]
This plugin remove sub block and create in new page, so the reference will be invalid.
plugin api `moveBlock` can keep reference no change, but it has some bug, it will fixed in logseq next release, and I will refactor this plugin with `moveBlock` api

**Comment by BlurBrain** [comment]
cool!!! looking forward to the new version then. Thanks for replying!

**Comment by hyrijk** [comment]
fixed in [1.3.0](https://github.com/hyrijk/logseq-plugin-block-to-page/releases/tag/v1.3.0)

**Comment by karlz97** [comment]
Cool! Just updated and tried it, works perfectly!!
