### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by gandalf34** [hyrijk/logseq-plugin-block-to-page#11]
as you can see from the attached video it doesn't work. I have also attached the console log . Hope this helps
[Logseq 2022-08-15 07-59-27.zip](https://github.com/hyrijk/logseq-plugin-block-to-page/files/9335196/Logseq.2022-08-15.07-59-27.zip)
[-1660539653148.log](https://github.com/hyrijk/logseq-plugin-block-to-page/files/9335202/-1660539653148.log)

.

**Comment by hyrijk** [comment]
it would do nothing if the block dont't have any child block
