### ISSUE TITLE
plugin not available after Version 0.5.7 on macOS

### ISSUE THREAD

**Issue by peizh** [hyrijk/logseq-plugin-block-to-page#4]
Slash command and block context menu disappeared with the latest plugin(version 0.0.5) and Logseq on MacOS(version 0.5.7).
Same as plugin [vipzhicheng/logseq\-plugin\-copy\-ref\-to\-journal](https://github.com/vipzhicheng/logseq-plugin-copy-ref-to-journal).
Perhaps because the API of Logseq changed?

**Comment by hyrijk** [comment]
The plugin worked with [Logseq-darwin-x64-0.5.7.zip](https://github.com/logseq/logseq/releases/download/0.5.7/Logseq-darwin-x64-0.5.7.zip), restarting logseq and try again?

**Comment by peizh** [comment]
> The plugin worked with [Logseq-darwin-x64-0.5.7.zip](https://github.com/logseq/logseq/releases/download/0.5.7/Logseq-darwin-x64-0.5.7.zip), restarting logseq and try again?

Thanks for the reply.
I'm using [Logseq-darwin-arm64-0.5.7.dmg](https://github.com/logseq/logseq/releases/download/0.5.7/Logseq-darwin-arm64-0.5.7.dmg) on M1 macOS Monterey 12.1.
I just did a clean reinstall of Logseq by trying `rm -fr ~/Library/Application\ Support/Logseq/*` and updated to 0.5.8. 
And I reinstalled the plugin in the market and have the same issue.
![image](https://user-images.githubusercontent.com/7479528/148342108-04881f2c-ade7-4467-b03e-66ffdacd4f97.png)
 
Seems some other plugins have normal context menu option showed up.
I don't know what to do now.🥲

**Comment by peizh** [comment]
> The plugin worked with [Logseq-darwin-x64-0.5.7.zip](https://github.com/logseq/logseq/releases/download/0.5.7/Logseq-darwin-x64-0.5.7.zip), restarting logseq and try again?

I did a clean uninstall and updated Logseq to 0.5.8. Now the issue is gone.
Thanks again for your reply and for your nice plugin.
