### ISSUE TITLE
block property with punctuation not work well

### ISSUE THREAD

**Issue by qbosen** [hyrijk/logseq-plugin-block-to-page#6]
![block into page bug](https://user-images.githubusercontent.com/15816040/151101931-2033d9b9-31e8-4c92-b348-85c883962319.gif)

Block properties with punctuation do not move correctly

**Comment by hyrijk** [comment]
fixed in [1.3.0](https://github.com/hyrijk/logseq-plugin-block-to-page/releases/tag/v1.3.0).
