### ISSUE TITLE
Fails

### ISSUE THREAD

**Issue by RhvdG** [hyrijk/logseq-plugin-block-to-page#8]
Both the slash-menu and the context-menu command fail. Nothing happens to the block, and no page is created

https://user-images.githubusercontent.com/34862159/154547605-494a684b-c4c4-44d6-99d6-5492a12d13d3.mov

.

**Comment by KelSolaar** [comment]
I had similar issues and lost the entire block content quite a few times with no apparent error or anything, at other times it did just work though. This makes the plugin highly unreliable and somehow dangerous to use.

**Comment by hyrijk** [comment]
It doesn't seem to work in the current version. If you find unexpected behavior, try undo several times until the original content is restored

**Comment by nuvic** [comment]
It seems to work now in [version 0.6.1](https://github.com/logseq/logseq/releases/tag/0.6.1)

**Comment by hyrijk** [comment]
> > It seems to work now in [version 0.6.1](https://github.com/logseq/logseq/releases/tag/0.6.1)
> 
> Not on my M1 iMac.

It should work in version 0.6.1.
If the selected block has no children, it will not do anything.
