### ISSUE TITLE
alert "some sub block may be referenced"

### ISSUE THREAD

**Issue by Imatvoid** [hyrijk/logseq-plugin-block-to-page#9]
[moveBlock](https://logseq.github.io/plugins/interfaces/IEditorProxy.html#moveBlock) API ?

**Comment by hyrijk** [comment]
#1 In  progress

**Comment by hyrijk** [comment]
using moveBlock api at [v1.3.0](https://github.com/hyrijk/logseq-plugin-block-to-page/releases/tag/v1.3.0)

**Comment by morrisxyang** [comment]
good work
